version: "0.1"

x-common-variables:
  PORT: "443"



services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - website
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - website
  # reverse_proxy:
  #   depends_on:
  #     - frontend
  #     - backend
  #   build: Dockerfile
  #   context: ./nginx
  #   ports:
  #   restart: always
  #   network: website
  
networks:
  website: